### ISSUE TITLE
sh脚本执行错误

### ISSUE THREAD

**Issue by Wind134** [AiCorein/arch-wine-neteasemusic#3]
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/deepinwine/tools/spark_get_tray_window", line 22, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/spark_get_tray_window", line 11, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.12/site-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
xprop: error: Invalid window id format: 0x0.
xprop: error: Invalid window id format: 0x0.
/opt/deepinwine/tools/spark_kill.sh: 行 65: /proc/2/environ: 权限不够
```
怎么解决啊，用的最新版。

**Comment by aicorein** [comment]
你是什么桌面环境，另外用的 xorg 还是 wayland

**Comment by Wind134** [comment]
> 你是什么桌面环境，另外用的 xorg 还是 wayland

不好意思，忘了贴信息了，KDE桌面，Wayland环境；具体配置：
```
OS: Arch Linux x86_64
Host: 82G2 (Yoga 14sITL 2021)
Kernel: Linux 6.6.46-1-lts
Uptime: 16 mins
Packages: 1887 (pacman)
Shell: zsh 5.9
Display (CSO1402): 2880x1800 @ 90 Hz (as 1440x900) in 14″ [Built-in]
DE: KDE Plasma 6.1.4
WM: KWin (Wayland)
WM Theme: Breeze 微风
Theme: Breeze (MacVenturaLight) [Qt], WhiteSur-Light [GTK2/3/4]
Icons: WhiteSur [Qt], WhiteSur [GTK2/3/4]
Font: OPPOSans (10pt) [Qt], OPPOSans (10pt) [GTK2/3/4]
Cursor: breeze (30px)
Terminal: konsole 24.5.2
Terminal Font: MesloLGLDZ Nerd Font Mono (10pt)
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 (8) @ 4.20 GHz
GPU 1: NVIDIA GeForce MX450 [Discrete]
GPU 2: Intel Iris Xe Graphics @ 1.30 GHz [Integrated]
Memory: 6.66 GiB / 15.41 GiB (43%)
```

**Comment by aicorein** [comment]
cat opt/apps/com.163.music.spark/files/run.sh 输出脚本内容我看一下
然后顺便看一下你的 wine 版本，可以用 pacman 看：

**Comment by aicorein** [comment]
![f7d6266b8a41c9483be56053bd0fe274](https://github.com/user-attachments/assets/73b3978a-4ca8-4ae4-8f6d-b762f284b575)

**Comment by Wind134** [comment]
> cat opt/apps/com.163.music.spark/files/run.sh 输出脚本内容我看一下 然后顺便看一下你的 wine 版本，可以用 pacman 看：

```
#!/bin/sh

#   Copyright (C) 2016 Deepin, Inc.
#
#   Author:     Li LongYu <lilongyu@linuxdeepin.com>
#               Peng Hao <penghao@linuxdeepin.com>
#
#
#   Copyright (C) 2022 The Spark Project
#
#
#   Modifier    shenmo <shenmo@spark-app.store>
#
#
#

#######################函数段。下文调用的额外功能会在此处声明

Get_Dist_Name()
{
    if grep -Eqii "Deepin" /etc/issue || grep -Eq "Deepin" /etc/*-release; then
        DISTRO='Deepin'
    elif grep -Eqi "UnionTech" /etc/issue || grep -Eq "UnionTech" /etc/*-release; then
        DISTRO='UniontechOS'
    else
         DISTRO='OtherOS'
        fi
}


####获得发行版名称

#########################预设值段

version_gt() { test "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1"; }
####用于比较版本？未实装
BOTTLENAME="Spark-CloudMusic"
APPVER="3.0.1.201795spark12.1"
EXEC_PATH="c:/Program Files/NetEase/CloudMusic/cloudmusic.exe"
##### 软件在wine中的启动路径
START_SHELL_PATH="/opt/deepinwine/tools/spark_run_v4.sh"
ENABLE_DOT_NET=""
####若使用spark-wine7-devel时需要用到.net，则请把ENABLE_DOT_NET设为true，同时在依赖中写spark-wine7-mono
export MIME_TYPE=""
export WINE_WMCLASS=cloudmusic.exe
export DEB_PACKAGE_NAME="com.163.music.spark"
####这里写包名才能在启动的时候正确找到files.7z,似乎也和杀残留进程有关
export APPRUN_CMD="spark-wine-wow"
#####wine启动指令，建议
##例如我的wine应用是使用的dwine6的32位容器，那么我要填LD_LIBRARY_PATH=$LD_LIBRARY;/opt/deepin-wine6-stable/lib
## 如果用不到就不填，不要删除前面的注释用的#

export SPECIFY_SHELL_DIR=`dirname $START_SHELL_PATH`

ARCHIVE_FILE_DIR="/opt/apps/$DEB_PACKAGE_NAME/files"

export WINEDLLPATH=/opt/$APPRUN_CMD/lib/wine/i386-unix:/opt/$APPRUN_CMD/lib/wine/x86_64-unix

export WINEPREDLL="$ARCHIVE_FILE_DIR/dlls"

DISABLE_ATTACH_FILE_DIALOG=""
##默认为空。若为1，则不使用系统自带的文件选择，而是使用wine的
##对于deepin/UOS，大部分的应用都不需要使用wine的，如果有需求（比如wine应用选择的限定种类文件系统的文管不支持）
##请填1。
##注意：因为非DDE的环境不确定，所以默认会在非Deepin/UOS发行版上禁用这个功能。如果你确认在适配的发行版上可以正常启动，请注释或者删除下面这段

##############<<<<<<<<<禁用文件选择工具开始
Get_Dist_Name
#此功能实现参见开头函数段
if [ "$DISTRO" != "Deepin" ] && [ "$DISTRO" != "UniontechOS" ];then
DISABLE_ATTACH_FILE_DIALOG=""
echo "非deepin/UOS，默认关闭系统自带的文件选择工具，使用Wine的"
echo "如果你想改变这个行为，请到/opt/apps/$DEB_PACKAGE_NAME/files/$0处修改"
echo "To打包者：如果你要打开自带请注意在适配的发行版上进行测试"
echo "To用户：打包者没有打开这个功能，这证明启用这个功能可能造成运行问题。如果你要修改这个行为，请确保你有一定的动手能力"
fi
##############>>>>>>>>>禁用文件选择工具结束

##############<<<<<<<<<屏蔽mono和gecko安装器开始
##默认屏蔽mono和gecko安装器
if [ "$APPRUN_CMD" = "spark-wine7-devel" ] || [ "$APPRUN_CMD" = "spark-wine" ] && [ -z "$ENABLE_DOT_NET" ];then

export WINEDLLOVERRIDES="mscoree=d,mshtml=d"
export WINEDLLOVERRIDES="control.exe=d"

#### "为了降低打包体积，默认关闭gecko和momo，如有需要，注释此行（仅对spark-wine7-devel有效）"

fi
##############>>>>>>>>>屏蔽mono和gecko安装器结束

#########################执行段




if [ -z "$DISABLE_ATTACH_FILE_DIALOG" ];then
    export ATTACH_FILE_DIALOG=1
fi

if [ -n "$EXPORT_ENVS" ];then
    export $EXPORT_ENVS
fi

if [ -n "$EXEC_PATH" ];then
    if [ -z "${EXEC_PATH##*.lnk*}" ];then
        $START_SHELL_PATH $BOTTLENAME $APPVER "C:/windows/command/start.exe" "/Unix" "$EXEC_PATH" "$@"
    else
        $START_SHELL_PATH $BOTTLENAME $APPVER "C:/windows/command/start.exe" "/Unix" "$EXEC_PATH" "$@"
    fi
else
    $START_SHELL_PATH $BOTTLENAME $APPVER "uninstaller.exe" "$@"
fi
```

下面这个wine版本应该是我刚更新的：
![image](https://github.com/user-attachments/assets/a145d61b-b31b-4e57-99e7-c9d245ae9af3)

**Comment by gklkf** [comment]
export APPRUN_CMD="spark-wine-wow"
改成
export APPRUN_CMD="wine"

**Comment by Wind134** [comment]
> export APPRUN_CMD="spark-wine-wow" 改成 export APPRUN_CMD="wine"

好了，解决！感谢！
